import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-background text-foreground">
        <header className="p-4 text-center border-b border-gray-300">
          <h1>My Next.js App</h1>
        </header>

        <main className="p-4">{children}</main>

        <footer className="p-4 text-center border-t border-gray-300 mt-4">
          <p>&copy; Next.js App Router Demo</p>
        </footer>
      </body>
    </html>
  );
}
